### ISSUE TITLE
Problem if the upload folder text is empty

### ISSUE THREAD

**Issue by dvoituron** [dvoituron/SsrsReportTransfert#5]
If the upload folder text zone is empty, and if you click on browse button, the application crash.

**Comment by dvoituron** [comment]
You can directly write path in this text zone. I will correct that in the next version.

**Comment by EricLogsdon** [comment]
I have crafted a fix for this that I am running locally. Would you like me to share the fix?

**Comment by dvoituron** [comment]
Yes, if course... Create a Pull Request, and I'll approved it.

**Comment by EricLogsdon** [comment]
OK. I will be away on vacation for a few days. I will do it then. It will be my first pull request, so I’ll be moving a bit slow to make sure I have it right.

--
Eric Logsdon
